name: Elliott Andrew
markdown: kramdown
parse_block_html: true
highlighter: rouge # or pygments or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:categories/:title
collections:
  currents:
defaults:
  - scope:
      path: "blog"
    values:
      image: true
