name: Elliott Andrew
markdown: kramdown
parse_block_html: true
highlighter: rouge # or pygments or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:categories/:title

image_url: /assets/imgs/test
thumb_url: /assets/imgs/thumbs

srcset:
  - 400
  - 800
  - 1200

thumb-srcset:
  - 568
  - 1136
  - 1704

sizes: '(min-width: 40em) 568px, 100vw'

mini_magick:
  thumb-small:
    source: /assets/imgs/thumbs/_import
    destination: /assets/imgs/thumbs/568
    resize: "568x568"
  thumb-medium:
    source: /assets/imgs/thumbs/_import
    destination: /assets/imgs/thumbs/1136
    resize: "1136x1136"
  thumb-large:
    source: /assets/imgs/thumbs/_import
    destination: /assets/imgs/thumbs/1704
    resize: "1704x1704"
